version: '3'

services:
    client:
        image: /mooz
        ports:
            - 80:80

    server:
        image: muzam1l/mooz-server
        ports:
            - '5000:5000'
        environment:
            - PORT=5000
