version: '3'

services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 80:80

    server:
        build:
            context: ./server
            dockerfile: ./Dockerfile
        ports:
            - '5000:5000'
        environment:
            - PORT=5000
