version: '3'

services:
    client:
        image: /bit-meet
        ports:
            - 80:80

    server:
        image: bit-meet/backend-server
        ports:
            - '5000:5000'
        environment:
            - PORT=5000
